#############################################################
###### HTTP
#########################################################
server:
  port: 9090

#############################################################
###### DATABASE
#########################################################
spring:
  data:
    mongodb:
      uri: mongodb://root:wishlist@localhost:27017/wishlist